### ISSUE TITLE
Home dir is not used when listing keys

### ISSUE THREAD

**Issue by psicus78** [soukoku/PgpSharp#1]
used package from nuget, version 0.1.2
When listing keys you don't consider KeyringFolder parameter, resulting in no keys found.
Added these lines  in public IEnumerable<KeyId> ListKeys(KeyTarget target) and fixed it.

Line 182
if (!string.IsNullOrWhiteSpace(KeyringFolder))
            {
                args += string.Format(" --homedir \"{0}\" ", KeyringFolder);
            }

**Comment by soukoku** [comment]
I've added the fix to new build.
